version: "3.9"

services:
  backend:
    build: .
    container_name: backend_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    environment:
    - CHOKIDAR_USEPOLLING=true

  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data: